name: Data Driven Tests WorkFlow

on: workflow_dispatch

jobs:
  run-login-test:
    runs-on: ubuntu-latest

    steps:
      - name: Pull the project into runner 
        uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Consider using a stable version like 11 or 17
    
      - name: Setup Maven
        uses: s4u/setup-maven@v3  # Corrected Maven setup action

      - name: Show Maven Version
        run: mvn -V  # Added a descriptive name for the command

      - name: Run the Web Tests
        run: |
          mvn clean test -Dtest=LoginUserTest
